;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        indent-for-tab-command
        org-end-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        avy-goto-char-2
        avy-goto-line
        ibuffer
        mc/toggle-cursor-on-click
        other-frame
        project-switch-project
        recompile
        toggle-input-method
        undo-redo
        ))
