# vim:fileencoding=utf-8:foldmethod=marker

font_size 13.0
cursor_shape block
shell_integration no-cursor
# cursor_text_color background
cursor_trail 3
enable_audio_bell no
enabled_layouts grid,stack,fat,horizontal,tall,vertical
map ctrl+enter toggle_layout stack

# BEGIN_KITTY_THEME
# Default
# include current-theme.conf
# END_KITTY_THEME

background_opacity 0.85
background_blur 15
