[settings]
minimum_release_age_excludes = [
  "pnpm",
]

[tools]
ast-grep = "0.45.0"
"cargo:askama_fmt" = "0.4.0"
"cargo:cargo-binstall" = "1.21.1"
go = "1.26.5"
"go:github.com/chrishrb/go-grip" = "0.9.2"
jjui = "0.10.9"
lazygit = "0.63.1"
node = "26"
pnpm = "11.18.0"
rust = "1.97.1"
usage = "4.1.0"
uv = "0.12.1"
