[tools]
"cargo:cargo-expand" = "latest"
"cargo:proximity-sort" = "latest"
jjui = "latest"
lua-language-server = "latest"
"npm:ccstatusline" = "latest"
uv = "latest"
taplo = "latest"
"npm:pyright" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
ruff = "latest"
gofumpt = "latest"
golangci-lint = "latest"
"npm:prettier" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:oxlint" = "latest"
"pipx:cpplint" = "latest"
clang-format = "latest"
"cargo:rustlings" = "latest"
"pipx:sqlfluff" = "latest"
"npm:marked" = "latest"
cmake = "latest"
"go:github.com/jessfraz/dockfmt" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
black = "latest"
"pipx:isort" = "latest"
"pipx:pytest" = "latest"
"pipx:pyflakes" = "latest"
"pipx:nose" = "latest"
"cargo:emacs-lsp-booster" = "latest"
cargo-binstall = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:stylelint" = "latest"
"npm:js-beautify" = "latest"
"go:github.com/chrishrb/go-grip" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
